(function(){'use strict';var q=[0,0,0,0],r=/[-+]?[0-9]*\.?[0-9]+%/g,t=/[-+]?[0-9]*\.?[0-9]+px/g,w=function(f,b,g,c,a){var d;if(b.gradientMode){a=[[a,a,0],[a,c-a,0],[g-a,c-a,0],[g-a,a,0]];if("radial"==b.gradientMode){(d=b.center)||(d="center");var h=f="center";var e=d.match(r);d=d.match(t);e&&1<e.length?(f=e[0],h=e[1]):d&&1<d.length&&(f=d[0],h=d[1]);f=u(f,a[0][0],a[3][0]);h=u(h,a[0][1],a[1][1]);e=b.shape;d=[.5*(a[0][0]+a[2][0]),.5*(a[0][0]+a[2][0])];var k=f<d[0]?a[2][0]:a[0][0];d=h<d[1]?a[1][1]:a[0][1];k=Math.abs(f-k);d=Math.abs(h-
d);var l=a[3][0]-a[0][0];a=a[1][1]-a[0][1];.001<Math.abs(l)&&(a/=l,k=Math.sqrt(k*k+d*d/(a*a)),d=a*k);a=k;e&&"farthest-corner"!=e&&(e=e.match(t))&&1<e.length&&(a=parseFloat(e[0]),d=parseFloat(e[1]));l=Math.max(a,d);e=document.createElement("canvas");e.width=g;e.height=c;k=e.getContext("2d");l=k.createRadialGradient(f,h,0,f,h,l);v(l,b.color);k.rect(0,0,g,c);d<a?(b=1,g=d/a):(g=1,b=a/d);k.save();k.transform(b,0,0,g,b*-f+f,g*-h+h);k.fillStyle=l;k.fill();k.restore();b=k.createPattern(e,"no-repeat")}else{g=
0;b.orientation&&(g=parseFloat(b.orientation)*Math.PI/180);isFinite(g)&&!isNaN(g)||(g=0);d=-1*g;g=[];h=[];c=[.5*(a[0][0]+a[2][0]),.5*(a[0][1]+a[2][1])];e=Math.tan(d);if(.001>Math.abs(Math.tan(.5*Math.PI-.001)-e))h=0<=Math.sin(d)?1:-1,a=.5*(a[2][1]-a[0][1]),g=[c[0],c[1]-h*a],h=[c[0],c[1]+h*a];else{d=0<=Math.cos(d)?1:-1;d=[d,d*e];for(var k=Infinity,l=-Infinity,p=0;4>p;p++){var m=[a[p][0]-c[0],a[p][1]-c[1]],m=e*m[1]+m[0],m=m/(1+e*e);var n=[m,m*e];m=(0<d[0]*n[0]+d[1]*n[1]?1:-1)*Math.sqrt(n[0]*n[0]+n[1]*
n[1]);n=[n[0]+c[0],n[1]+c[1]];m<k&&(g=n,k=m);m>l&&(h=n,l=m)}}a=f.createLinearGradient(g[0],g[1],h[0],h[1]);v(a,b.color);b=a}return b}return"rgba("+Math.floor(255*b[0])+","+Math.floor(255*b[1])+","+Math.floor(255*b[2])+","+b[3]+")"},v=function(f,b){if(f)for(var g=0;g<b.length;g++){var c=b[g].position/100,a=b[g].value;if(void 0===a.a||null===a.a)a.a=1;f.addColorStop(c,"rgba("+a.r+","+a.g+","+a.b+","+a.a+")")}},u=function(f,b,g){return f?0<=f.indexOf("%")?b+parseInt(f,10)/100*(g-b):0<=f.indexOf("px")?
b+parseInt(f,10):b+.5*(g-b):0};var x=function(){};goog.inherits(x,HTMLCanvasElement);
x.prototype.attachedCallback=function(){var f=this.getContext("2d"),b=this.width,g=this.height,c={};c.strokeWidth=parseFloat(this.getAttribute("stroke-width"))||0;c.strokeColor=JSON.parse(this.getAttribute("stroke-color"))||q;c.fillColor=JSON.parse(this.getAttribute("fill-color"))||q;c.tlRadius=parseFloat(this.getAttribute("tl-radius"))||0;c.trRadius=parseFloat(this.getAttribute("tr-radius"))||0;c.blRadius=parseFloat(this.getAttribute("bl-radius"))||0;c.brRadius=parseFloat(this.getAttribute("br-radius"))||
0;var a=c.strokeWidth;f.beginPath();var d=Math.ceil(a)-.5;c.fillColor&&(f.fillStyle=w(f,c.fillColor,b,g,a),f.lineWidth=a,y(c,d,f,b,g),f.fill(),f.closePath());f.beginPath();d=Math.ceil(.5*a)-.5;c.strokeColor&&(f.strokeStyle=w(f,c.strokeColor,b,g,0),f.lineWidth=a,y(c,d,f,b,g),f.stroke(),f.closePath())};x.prototype.attributeChangedCallback=function(){};
var y=function(f,b,g,c,a){var d=.5*c,h=.5*a,e=[b,b],k=f.tlRadius,l=f.trRadius,p=f.blRadius;f=f.brRadius;d=d<h?d:h;k>d&&(k=d);p>d&&(p=d);f>d&&(f=d);l>d&&(l=d);d=c-b;h=a-b;0>=k&&0>=p&&0>=f&&0>=l?g.rect(e[0],e[1],c-2*b,a-2*b):(c=k-b,0>c&&(c=0),e[1]+=c,.001>Math.abs(c)&&(e[1]=b),g.moveTo(e[0],e[1]),e=[b,h],c=p-b,0>c&&(c=0),e[1]-=c,g.lineTo(e[0],e[1]),.001<c&&g.arcTo(b,h,b+c,h,p-b),e=[d,h],c=f-b,0>c&&(c=0),e[0]-=c,g.lineTo(e[0],e[1]),.001<c&&g.arcTo(d,h,d,h-c,f-b),e=[d,b],c=l-b,0>c&&(c=0),e[1]+=c,g.lineTo(e[0],
e[1]),.001<c&&g.arcTo(d,b,d-c,b,l-b),e=[b,b],c=k-b,0>c&&(c=0),e[0]+=c,g.lineTo(e[0],e[1]),.001<c?g.arcTo(b,b,b,b+c,k-b):g.lineTo(b,2*b))};document.registerElement("gwd-rectangle",{prototype:x.prototype,"extends":"canvas"});}).call(this);
